## Activity 06: Filtering, Sorting, and Reshaping

Following up on the last activity, we are asked to deliver some more complex operations.   
We will, therefore, continue to work with the same dataset, our `world_population.csv`.

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import pandas as pd

In [2]:
# loading the Dataset
dataset = pd.read_csv('./data/world_population.csv', index_col=0)

In [3]:
# looking at the data
dataset[:2]

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,307.972222,312.366667,314.983333,316.827778,318.666667,320.622222,...,562.322222,563.011111,563.422222,564.427778,566.311111,568.850000,571.783333,574.672222,577.161111,NaN
Andorra,AND,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,30.587234,32.714894,34.914894,37.170213,39.470213,41.800000,...,180.591489,182.161702,181.859574,179.614894,175.161702,168.757447,161.493617,154.863830,149.942553,NaN

---

#### Filtering

To get better insights into our dataset, we want to only look at the value that fulfills certain conditions.   
Our client reaches out to us and asks us to provide lists of values that fulfills these conditions:
- a new dataset that only contains 1961, 2000, and 2015 as columns
- all countries that in 2000 had a greater population density than 500
- a new dataset that only contains years 2000 and later
- a new dataset that only contains countries that start with `A`
- a new dataset that only contains countries that contain the word `land`

In [4]:
# filtering columns 1961, 2000, and 2015
dataset.filter(items=['1961', '2000', '2015'])

                        1961        2000        2015
Country Name
Aruba             307.972222  504.766667  577.161111
Andorra            30.587234  139.146809  149.942553
Afghanistan        14.038148   30.177894   49.821649
Angola              4.305195   12.078798   20.070565
Albania            60.576642  112.738212  105.444051
...                      ...         ...         ...
Yemen, Rep.         9.946897   33.704981   50.821477
South Africa       14.796892   36.271010   45.303251
Congo, Dem. Rep.    6.897825   21.194356   34.082536
Zambia              4.227724   14.239121   21.807890
Zimbabwe           10.021037   32.312217   40.332819

[264 rows x 3 columns]

In [5]:
# filtering countries that had a greater population density than 500 in 2000
dataset.filter(dataset[['2000']] > 500)

                        2000
Country Name
Aruba             504.766667
Andorra           139.146809
Afghanistan        30.177894
Angola             12.078798
Albania           112.738212
...                      ...
Yemen, Rep.        33.704981
South Africa       36.271010
Congo, Dem. Rep.   21.194356
Zambia             14.239121
Zimbabwe           32.312217

[264 rows x 1 columns]

In [11]:
# filtering for years 2000 and later
dataset.filter(like='200', axis=1)

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
Country Name,,,,,,,,,,
Aruba,504.766667,516.077778,527.750000,538.972222,548.566667,555.727778,560.166667,562.322222,563.011111,563.422222
Andorra,139.146809,144.191489,151.161702,159.112766,166.674468,172.814894,177.389362,180.591489,182.161702,181.859574
Afghanistan,30.177894,31.448029,32.912231,34.475030,35.995236,37.373936,38.574296,39.637202,40.634655,41.674005
Angola,12.078798,12.483188,12.921871,13.388462,13.873025,14.368286,14.872437,15.387749,15.915819,16.459536
Albania,112.738212,111.685146,111.350730,110.934891,110.472226,109.908285,109.217044,108.394781,107.566204,106.843759
...,...,...,...,...,...,...,...,...,...,...
"Yemen, Rep.",33.704981,34.672968,35.668877,36.695290,37.751420,38.836269,39.952976,41.102913,42.280241,43.476383
South Africa,36.271010,37.020945,37.464736,37.947742,38.448180,38.966658,39.503814,40.060326,40.636905,41.234300
"Congo, Dem. Rep.",21.194356,21.812053,22.483583,23.202932,23.958384,24.741199,25.551638,26.393275,27.264188,28.162192
Zambia,14.239121,14.610417,14.985375,15.370137,15.773194,16.200905,16.655469,17.135926,17.641587,18.170609
Zimbabwe,32.312217,32.581073,32.807111,33.020969,33.263094,33.564477,33.935484,34.374559,34.885516,35.468520

In [13]:
# # filtering countries that start with A
dataset.filter(regex='^A', axis=0)

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,307.972222,312.366667,314.983333,316.827778,318.666667,320.622222,...,562.322222,563.011111,563.422222,564.427778,566.311111,568.850000,571.783333,574.672222,577.161111,NaN
Andorra,AND,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,30.587234,32.714894,34.914894,37.170213,39.470213,41.800000,...,180.591489,182.161702,181.859574,179.614894,175.161702,168.757447,161.493617,154.863830,149.942553,NaN
Afghanistan,AFG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,14.038148,14.312061,14.599692,14.901579,15.218206,15.545203,...,39.637202,40.634655,41.674005,42.830327,44.127634,45.533197,46.997059,48.444546,49.821649,NaN
Angola,AGO,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,4.305195,4.384299,4.464433,4.544558,4.624228,4.703271,...,15.387749,15.915819,16.459536,17.020898,17.600302,18.196544,18.808215,19.433323,20.070565,NaN
Albania,ALB,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,60.576642,62.456898,64.329234,66.209307,68.058066,69.874927,...,108.394781,107.566204,106.843759,106.314635,106.013869,105.848431,105.717226,105.607810,105.444051,NaN
Arab World,ARB,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,6.978698,7.171974,7.372223,7.579523,7.793882,8.016037,...,24.131584,24.727571,25.331750,25.923338,26.504736,27.075214,27.640621,28.207253,28.779858,NaN
Argentina,ARG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,7.656358,7.778624,7.900729,8.022073,8.142460,8.261347,...,14.605199,14.755730,14.908024,15.063041,15.221167,15.381802,15.543706,15.705113,15.864696,NaN
Armenia,ARM,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,67.939550,70.325606,72.723112,75.101264,77.437654,79.714612,...,104.956691,104.496979,104.183632,104.091886,104.249526,104.613242,105.099824,105.590235,105.996207,NaN
American Samoa,ASM,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,102.390000,105.590000,109.415000,113.505000,117.590000,121.600000,...,289.520000,285.155000,281.130000,278.180000,276.580000,276.135000,276.510000,277.170000,277.690000,NaN
Antigua and Barbuda,ATG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,125.915909,127.979545,130.381818,132.954545,135.575000,138.222727,...,191.811364,193.977273,196.136364,198.256818,200.345455,202.429545,204.511364,206.590909,208.677273,NaN
Australia,AUS,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,1.364565,1.398279,1.425354,1.453601,1.482369,1.516603,...,2.711115,2.765995,2.823594,2.867859,2.907986,2.958522,3.009171,3.054305,3.095579,NaN
Austria,AUT,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,85.811322,86.338871,86.895265,87.476399,88.046609,88.666336,...,100.456381,100.771343,101.044229,101.299694,101.650350,102.132190,102.741697,103.495353,104.337619,NaN
Azerbaijan,AZE,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,48.429167,50.080609,51.760037,53.422414,55.033935,56.580807,...,103.853369,106.059763,108.291290,109.542344,110.976336,112.460790,113.923481,115.354396,116.761018,NaN
Algeria,DZA,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,4.788457,4.908240,5.032090,5.162601,5.301567,5.449910,...,14.385269,14.615810,14.863835,15.130182,15.416096,15.719359,16.032873,16.347013,16.654429,NaN

In [14]:
# filtering countries that contain the word land
dataset.filter(like='land', axis=0)

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country Name,,,,,,,,,,,,,,,,,,,,,
Switzerland,CHE,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,137.479609,141.009285,144.056036,146.458915,148.160089,149.716707,...,191.090115,193.533632,195.966975,198.018752,200.232766,202.370204,204.710649,207.223631,209.711914,NaN
Channel Islands,CHI,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,569.067010,574.551546,580.386598,586.484536,592.742268,599.103093,...,806.783505,812.304124,817.592784,839.910526,844.678947,849.136842,853.357895,857.457895,861.536842,NaN
Cayman Islands,CYM,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,33.441667,33.925000,34.283333,34.579167,34.879167,35.175000,...,214.500000,220.520833,226.187500,231.287500,235.750000,239.675000,243.204167,246.550000,249.862500,NaN
Finland,FIN,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,14.645934,14.745865,14.850484,14.933330,14.983197,15.039460,...,17.391956,17.484038,17.567855,17.648411,17.730995,17.815562,17.897831,17.972003,18.039465,NaN
Faroe Islands,FRO,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,24.878223,25.181232,25.465616,25.749284,26.047994,26.363897,...,34.813037,34.834527,34.823066,34.790115,34.736390,34.665473,34.593123,34.542264,34.526504,NaN
Greenland,GRL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.098625,0.102429,0.106526,0.110038,0.114721,0.118525,...,0.137788,0.137235,0.137223,0.138641,0.138604,0.138409,0.137612,0.137154,0.136713,NaN
Ireland,IRL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,40.998694,41.167804,41.408768,41.610539,41.766584,41.933517,...,63.854580,65.169749,65.835027,66.194731,66.436261,66.582915,66.748352,67.023153,67.363957,NaN
Iceland,ISL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,1.785825,1.819232,1.851900,1.885117,1.918065,1.950823,...,3.107890,3.166224,3.177047,3.172479,3.182185,3.199162,3.229566,3.265696,3.299980,NaN
Marshall Islands,MHL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,289.644444,290.116667,290.672222,291.266667,291.894444,292.572222,293.255556,293.877778,294.405556,NaN
Northern Mariana Islands,MNP,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,129.980435,124.658696,120.165217,117.086957,115.726087,115.900000,117.106522,118.567391,119.717391,NaN
Netherlands,NLD,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,344.748578,349.694579,354.442121,359.215640,364.180450,368.964781,...,485.239810,487.132494,490.079692,492.599881,495.049644,496.884994,499.092129,500.891238,503.015147,NaN
New Zealand,NZL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,9.189548,9.426152,9.615282,9.818845,9.982150,10.162546,...,16.041168,16.177889,16.340435,16.523110,16.649577,16.741104,16.870229,17.126961,17.453572,NaN
Poland,POL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,97.828855,98.953606,100.270985,101.666558,102.663979,103.434653,...,124.446853,124.471952,124.564461,124.209201,124.296297,124.300059,124.229111,124.136165,124.096189,NaN
Pacific island small states,PSS,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,14.225437,14.702879,15.194225,15.683583,16.159147,16.617213,...,33.094237,33.542040,33.996059,34.445810,34.888614,35.326822,35.760654,36.191791,36.621355,NaN
Solomon Islands,SLB,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,4.337370,4.468310,4.603894,4.744087,4.889139,5.038478,...,17.580386,17.985352,18.391104,18.798750,19.208574,19.619936,20.031618,20.441979,20.849982,NaN
Swaziland,SWZ,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,20.786163,21.262733,21.743663,22.242733,22.770872,23.331105,...,65.979826,67.078488,68.228430,69.369070,70.491744,71.610116,72.711686,73.785581,74.823837,NaN
Turks and Caicos Islands,TCA,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,6.063158,6.065263,6.043158,6.005263,5.967368,5.925263,...,30.145263,31.032632,31.838947,32.624211,33.396842,34.136842,34.845263,35.515789,36.146316,NaN
Thailand,THA,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,55.245176,56.922306,58.656546,60.446147,62.288943,64.180346,...,129.878393,130.073509,130.259345,130.540868,130.953743,131.464953,132.027290,132.564699,133.021510,NaN
British Virgin Islands,VGB,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,54.380000,55.320000,56.366667,57.520000,58.753333,60.060000,...,164.900000,170.693333,176.333333,181.486667,186.040000,190.073333,193.720000,197.233333,200.780000,NaN
Virgin Islands (U.S.),VIR,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,97.428571,103.714286,110.571429,118.000000,125.714286,135.142857,...,306.922857,305.974286,304.877143,303.620000,302.240000,300.785714,299.248571,297.628571,295.925714,NaN

---

#### Sorting

They also want to get some better insights into their data so they ask you to also deliver these datasets to understand the population growth better:
- values sorted in ascending order by 1961
- values sorted in ascending order by 2015
- values sorted in descending order by 2015

In [15]:
# values sorted by column 1961
dataset.sort_values(by=['1961'])

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country Name,,,,,,,,,,,,,,,,,,,,,
Greenland,GRL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.098625,0.102429,0.106526,0.110038,0.114721,0.118525,...,0.137788,0.137235,0.137223,0.138641,0.138604,0.138409,0.137612,0.137154,0.136713,NaN
Mongolia,MNG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.632212,0.650975,0.670964,0.691648,0.712637,0.733773,...,1.668926,1.692671,1.718358,1.746091,1.775969,1.807680,1.840401,1.873034,1.904744,NaN
Namibia,NAM,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.749775,0.768451,0.787897,0.808096,0.829055,0.850631,...,2.530304,2.569815,2.614336,2.664484,2.720987,2.783521,2.850262,2.918605,2.986590,NaN
Libya,LBY,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.843320,0.873067,0.904845,0.939049,0.975968,1.015652,...,3.420095,3.479899,3.528581,3.560986,3.574032,3.571049,3.561151,3.557171,3.568227,NaN
Mauritania,MRT,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.856916,0.882092,0.908134,0.935040,0.962810,0.991443,...,3.229150,3.312848,3.397620,3.484428,3.573514,3.664565,3.757334,3.851387,3.946409,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Palau,PLW,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.734783,43.971739,44.226087,44.500000,44.795652,45.121739,45.476087,45.863043,46.284783,NaN
Serbia,SRB,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84.399485,84.040956,83.704631,83.368809,82.713229,82.312794,81.913240,81.529568,81.159925,NaN
South Sudan,SSD,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sint Maarten (Dutch part),SXM,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1160.647059,1189.941176,1150.970588,1043.352941,983.382353,1018.823529,1076.676471,1108.382353,1141.676471,NaN
West Bank and Gaza,PSE,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,580.481063,597.456478,614.986379,633.073422,652.334053,672.242691,692.608970,713.402326,734.575249,NaN

In [16]:
# values sorted by column 2015
dataset.sort_values(by=['2015'])

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country Name,,,,,,,,,,,,,,,,,,,,,
Greenland,GRL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.098625,0.102429,0.106526,0.110038,0.114721,0.118525,...,0.137788,0.137235,0.137223,0.138641,0.138604,0.138409,0.137612,0.137154,0.136713,NaN
Mongolia,MNG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.632212,0.650975,0.670964,0.691648,0.712637,0.733773,...,1.668926,1.692671,1.718358,1.746091,1.775969,1.807680,1.840401,1.873034,1.904744,NaN
Namibia,NAM,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.749775,0.768451,0.787897,0.808096,0.829055,0.850631,...,2.530304,2.569815,2.614336,2.664484,2.720987,2.783521,2.850262,2.918605,2.986590,NaN
Australia,AUS,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,1.364565,1.398279,1.425354,1.453601,1.482369,1.516603,...,2.711115,2.765995,2.823594,2.867859,2.907986,2.958522,3.009171,3.054305,3.095579,NaN
Iceland,ISL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,1.785825,1.819232,1.851900,1.885117,1.918065,1.950823,...,3.107890,3.166224,3.177047,3.172479,3.182185,3.199162,3.229566,3.265696,3.299980,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Monaco,MCO,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,11406.000000,11521.000000,11584.500000,11618.500000,11641.500000,11652.000000,...,17523.000000,17865.500000,18175.500000,18422.500000,18594.500000,18702.000000,18764.000000,18811.500000,18865.500000,NaN
"Macao SAR, China",MAC,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,8756.750000,9051.250000,9435.150000,9876.150000,10345.500000,10843.650000,...,16884.315068,17372.397260,17674.745763,18000.875421,18283.678930,18654.280936,18747.722772,19073.069307,19392.937294,NaN
Eritrea,ERI,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,14.270267,14.617040,14.976941,15.349475,15.734525,16.132010,...,43.626723,44.560772,45.480683,46.432317,47.421465,NaN,NaN,NaN,NaN,NaN
Not classified,INX,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Sudan,SSD,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Note:**   
Comparisons like this are very valuable to get a good understanding not only of your dataset but also the underlying data itself.   
For example, here we can see that the ranking of the lowest densely populated countries changed.

In [17]:
# values sorted by column 2015 in descending order
dataset.sort_values(by=['2015'], ascending=False)

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Country Name,,,,,,,,,,,,,,,,,,,,,
"Macao SAR, China",MAC,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,8756.750000,9051.250000,9435.150000,9876.150000,10345.500000,10843.650000,...,16884.315068,17372.397260,17674.745763,18000.875421,18283.678930,18654.280936,18747.722772,19073.069307,19392.937294,NaN
Monaco,MCO,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,11406.000000,11521.000000,11584.500000,11618.500000,11641.500000,11652.000000,...,17523.000000,17865.500000,18175.500000,18422.500000,18594.500000,18702.000000,18764.000000,18811.500000,18865.500000,NaN
Singapore,SGP,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,2540.895522,2612.238806,2679.104478,2748.656716,2816.268657,2887.164179,...,6602.300719,6913.422857,7125.104286,7231.811966,7363.193182,7524.698300,7636.721358,7736.526167,7828.857143,NaN
"Hong Kong SAR, China",HKG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,3105.980392,3240.392157,3353.823529,3435.882353,3527.352941,3558.725490,...,6586.952381,6626.476190,6640.761905,6689.714286,6734.857143,6813.904762,6845.238095,6896.857143,6957.809524,NaN
Gibraltar,GIB,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,2179.700000,2213.300000,2251.000000,2289.400000,2325.600000,2359.000000,...,2977.000000,3008.900000,3040.700000,3073.200000,3106.700000,3140.200000,3172.000000,3199.700000,3221.700000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mongolia,MNG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.632212,0.650975,0.670964,0.691648,0.712637,0.733773,...,1.668926,1.692671,1.718358,1.746091,1.775969,1.807680,1.840401,1.873034,1.904744,NaN
Greenland,GRL,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,0.098625,0.102429,0.106526,0.110038,0.114721,0.118525,...,0.137788,0.137235,0.137223,0.138641,0.138604,0.138409,0.137612,0.137154,0.136713,NaN
Eritrea,ERI,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,14.270267,14.617040,14.976941,15.349475,15.734525,16.132010,...,43.626723,44.560772,45.480683,46.432317,47.421465,NaN,NaN,NaN,NaN,NaN
Not classified,INX,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Sudan,SSD,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

---

#### Reshaping

In order to create a visualization that focuses on 2015, they ask you to create a subset of your FataFrame which only contains one row that which holds all the values for the year 2015 mapped to the country codes as columns.   

They've sent you this scribble:   
```
Country Code    ABW    AFG    AGO   ...
----------------------------------------
        2015    577     49     20   ...
```

> They were lazy so they didn't write the digits after the comma. Make sure to keep the original values

In [31]:
# reshaping to 2015 as row and country codes as columns
dataset_2015 = dataset[["Country Code", "2015"]]
# dataset_2015
dataset_2015.pivot(index=["2015"], columns="Country Code", values="2015")

Country Code,ABW,AFG,AGO,ALB,AND,ARB,ARE,ARG,ARM,ASM,...,VGB,VIR,VNM,VUT,WLD,WSM,YEM,ZAF,ZMB,ZWE
2015,,,,,,,,,,,,,,,,,,,,,
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0.136713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1.904744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.986590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.095579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3221.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6957.809524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7828.857143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18865.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19392.937294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN